# Generated by Django 5.0.3 on 2024-03-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('executionDate', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('progress', models.IntegerField()),
                ('finishDate', models.DateField()),
            ],
        ),
    ]
