# Generated by Django 4.1 on 2024-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='executionDate',
            field=models.DateTimeField(),
        ),
    ]
