# Generated by Django 5.0.3 on 2024-03-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
    ]
