# Generated by Django 5.0.3 on 2024-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Legos', max_length=50),
            preserve_default=False,
        ),
    ]
