# Generated by Django 5.0.3 on 2024-03-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_delete_user_event_important_event_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
    ]
