# Generated by Django 5.0.3 on 2024-03-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='Task',
        ),
    ]
