# Generated by Django 5.0.3 on 2024-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
